Imported Upstream version 0.9.2

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@
 AC_INIT(configure.in)
 
     AM_CONFIG_HEADER(config.h)
-    AM_INIT_AUTOMAKE(suricata, 0.9.1)
+    AM_INIT_AUTOMAKE(suricata, 0.9.2)
 
     AC_LANG_C
     AC_PROG_CC_C99
@@ -52,6 +52,7 @@ AC_INIT(configure.in)
 
     CFLAGS="$CFLAGS -Wall -fno-strict-aliasing"
     CFLAGS="$CFLAGS -Wno-unused-parameter"
+    CFLAGS="$CFLAGS -std=gnu99"
 
 # Checks for programs.
     AC_PROG_AWK
@@ -120,11 +121,9 @@ AC_INIT(configure.in)
 #These flags seem to be supported on CentOS 5+, Ubuntu 8.04+, and FedoreCore 11+
 #Options are taken from https://wiki.ubuntu.com/CompilerFlags
     AC_ARG_ENABLE(gccprotect,
-            [  --enable-gccprotect  Detect and use gcc hardening options],
-            [ enable_gccprotect=yes
-            ])
+           AS_HELP_STRING([--enable-gccprotect], [Detect and use gcc hardening options]),,[enable_gccprotect=no])
 
-    if test "$enable_gccprotect" = "yes"; then
+    AS_IF([test "x$enable_gccprotect" = "xyes"], [
         #buffer overflow protection
         AC_MSG_CHECKING(for -fstack-protector)
         TMPCFLAGS="${CFLAGS}"
@@ -172,36 +171,24 @@ AC_INIT(configure.in)
 
         CFLAGS="${CFLAGS} ${SECCFLAGS}"
         LDFLAGS="${LDFLAGS} ${SECLDFLAGS}"
-    fi
+    ])
 
 #enable profile generation
     AC_ARG_ENABLE(gccprofile,
-            [  --enable-gccprofile Enable gcc profile info i.e -pg flag is set],
-            [ enable_gccprofile=yes
-            ])
-
-    if test "$enable_gccprofile" = "yes"; then
-    CFLAGS="${CFLAGS} -pg"
-    fi
+           AS_HELP_STRING([--enable-gccprofile], [Enable gcc profile info i.e -pg flag is set]),,[enable_gccprofile=no])
+    AS_IF([test "x$enable_gccprofile" = "xyes"], [
+        CFLAGS="${CFLAGS} -pg"
+    ])
 
 #enable gcc march=native gcc 4.2 or later
     AC_ARG_ENABLE(gccmarch_native,
-            [  --enable-gccmarch-native Enable gcc march=native gcc 4.2 and later only],
-            [ enable_gccmarch_native=yes
-            ])
-
-    if test "$enable_gccmarch_native" = "yes"; then
+           AS_HELP_STRING([--enable-gccmarch-native], [Enable gcc march=native gcc 4.2 and later only]),,[enable_gccmarch_native=yes])
+    AS_IF([test "x$enable_gccmarch_native" = "xyes"], [
         if test "$gccvernum" -ge "402"; then
                 dnl gcc 4.2 or later
                 CFLAGS="$CFLAGS -march=native"
-        else
-                echo
-                echo "   You specified --enable-gccmarch-native but looks like you are running gcc < 4.2"
-                echo "   Please update your version of gcc or remove this option from configure."
-                echo
-                exit 1
         fi
-    fi
+    ])
 
 #libpcre
     AC_ARG_WITH(libpcre_includes,
@@ -321,11 +308,9 @@ AC_INIT(configure.in)
 
 #enable support for NFQUEUE
     AC_ARG_ENABLE(nfqueue,
-            [  --enable-nfqueue  Enable NFQUEUE support for inline IDP],
-            [ enable_nfqueue=yes
-            ])
-    if test "$enable_nfqueue" = "yes"; then
-    CFLAGS="$CFLAGS -DNFQ"
+           AS_HELP_STRING([--enable-nfqueue], [Enable NFQUEUE support for inline IDP]),,[enable_nfqueue=no])
+    AS_IF([test "x$enable_nfqueue" = "xyes"], [
+        CFLAGS="$CFLAGS -DNFQ"
 
 #libnfnetlink
 case $host in
@@ -416,24 +401,18 @@ esac
     echo
     exit 1 
     fi
-    fi
-
+])
 #enable support for IPFW
     AC_ARG_ENABLE(ipfw,
-            [  --enable-ipfw  Enable FreeBSD IPFW support for inline IDP],
-            [ enable_ipfw=yes
-            ])
-    if test "$enable_ipfw" = "yes"; then
+            AS_HELP_STRING([--enable-ipfw], [Enable FreeBSD IPFW support for inline IDP]),,[enable_ipfw=no])
+    AS_IF([test "x$enable_ipfw" = "xyes"], [
         CFLAGS="$CFLAGS -DIPFW"
-    fi
+    ])
 
 #prelude
-
     AC_ARG_ENABLE(prelude,
-            [  --enable-prelude  Enable Prelude support for alerts],
-            [ enable_prelude=yes
-            ])
-    if test "$enable_prelude" = "yes"; then
+            AS_HELP_STRING([--enable-prelude], [Enable Prelude support for alerts]),,[enable_prelude=no])
+    AS_IF([test "x$enable_prelude" = "xyes"], [
         CFLAGS="$CFLAGS -DPRELUDE"
         AM_PATH_LIBPRELUDE(0.9.9, , AC_MSG_ERROR(Cannot find libprelude: Is libprelude-config in the path?), no)
         if test "x${LIBPRELUDE_CFLAGS}" != "x"; then
@@ -447,9 +426,7 @@ esac
         if test "x${LIBPRELUDE_LIBS}" != "x"; then
             LDFLAGS="${LDFLAGS} ${LIBPRELUDE_LIBS}"
         fi
-
-    fi
-
+    ])
 
 #libnet
     AC_ARG_WITH(libnet_includes,
@@ -527,12 +504,10 @@ esac
 # libpfring (currently only supported for libpcap enabled pfring)
 # Error on the side of caution. If libpfring enabled pcap is being used and we don't link against -lpfring compilation will fail.
     AC_ARG_ENABLE(pfring,
-            [  --enable-pfring  Enable Native PF_RING support],
-            [ enable_pfring=yes
-            ])
-    if test "$enable_pfring" = "yes"; then
-    CFLAGS="$CFLAGS -DHAVE_PFRING"
-    fi
+           AS_HELP_STRING([--enable-pfring], [Enable Native PF_RING support]),,[enable_pfring=no])
+    AS_IF([test "x$enable_pfring" = "xyes"], [
+        CFLAGS="$CFLAGS -DHAVE_PFRING"
+    ])
 
 #We have to set CFLAGS for AC_TRY_COMPILE as it doesn't pay attention to CPPFLAGS
     AC_ARG_WITH(libpfring_includes,
@@ -553,7 +528,7 @@ esac
     LIBPFRING=""
     AC_CHECK_LIB(pfring, pfring_set_cluster,, LIBPFRING="no")
     if test "$LIBPFRING" = "no"; then
-        if test "enable_pfring" = "yes"; then
+        if test "x$enable_pfring" = "xyes"; then
         echo
         echo "   ERROR! --enable-pfring was passed but the library was not found or version is >4, go get it"
         echo "   from http://www.ntop.org/PF_RING.html"
@@ -612,90 +587,92 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
     fi
     LIBS="${TMPLIBS}"
 
+#Appears as if pcap_set_buffer_size is linux only?
+    LIBPCAPSBUFF=""
+#To prevent duping the lib link we reset LIBS after this check. Setting action-if-found to NULL doesn't seem to work
+#see: http://blog.flameeyes.eu/2008/04/29/i-consider-ac_check_lib-harmful
+    TMPLIBS="${LIBS}"
+    AC_CHECK_LIB(pcap, pcap_set_buffer_size,, LPCAPSBUFF="no")
+    if test "$LPCAPSBUFF" != "no"; then
+    CFLAGS="${CFLAGS} -DHAVE_PCAP_SET_BUFF"
+    fi
+    LIBS="${TMPLIBS}"
+
 # enable the running of unit tests
     AC_ARG_ENABLE(unittests,
-            [  --enable-unittests  Enable compilation of the unit tests],
-            [ enable_unittests=yes
-            ])
-    if test "$enable_unittests" = "yes"; then
-    CFLAGS="${CFLAGS} -DUNITTESTS"
-    fi
+           AS_HELP_STRING([--enable-unittests], [Enable compilation of the unit tests]),,[enable_unittests=no])
+    AS_IF([test "x$enable_unittests" = "xyes"], [
+        UT_ENABLED="yes"
+        CFLAGS="${CFLAGS} -DUNITTESTS"
+    ])
 
 # enable native timeval for unified alert output
     AC_ARG_ENABLE(unified-native-timeval,
-            [  --enable-unified-native-timeval  Use native timeval for unified outputs],
-            [ enable_unified_native_timeval=yes
-            ])
-    if test "$enable_unified_native_timeval" = "yes"; then
-    CFLAGS="${CFLAGS} -DUNIFIED_NATIVE_TIMEVAL"
-    fi
+           AS_HELP_STRING([--enable-unified-native-timeval], [Use native timeval for unified outputs]),,[enable_unified_native_timeval=no])
+    AS_IF([test "x$enable_unified_native_timeval" = "xyes"], [
+        CFLAGS="${CFLAGS} -DUNIFIED_NATIVE_TIMEVAL"
+    ])
 
 # enable debug output
     AC_ARG_ENABLE(debug,
-            [  --enable-debug  Enable debug output],
-            [ enable_debug=yes
-            ])
-    if test "$enable_debug" = "yes"; then
-    CFLAGS="${CFLAGS} -DDEBUG"
-    fi
+           AS_HELP_STRING([--enable-debug], [Enable debug output]),,[enable_debug=no])
+    AS_IF([test "x$enable_debug" = "xyes"], [
+        CFLAGS="${CFLAGS} -DDEBUG"
+    ])
 
 #libhtp
-    AC_ARG_ENABLE(nonbundled-htp,
-            [  --enable-nonbundled-htp Enable the use of an already installed version of htp],
-            [enable_non_bundled_htp=yes],[enable_non_bundled_htp=no]
-            )
-    if test "$enable_non_bundled_htp" = "yes"; then
-    AC_ARG_WITH(libhtp_includes,
-            [  --with-libhtp-includes=DIR  libhtp include directory],
-            [with_libhtp_includes="$withval"],[with_libhtp_includes=no])
-    AC_ARG_WITH(libhtp_libraries,
-            [  --with-libhtp-libraries=DIR    libhtp library directory],
-            [with_libhtp_libraries="$withval"],[with_libhtp_libraries="no"])
+    AC_ARG_ENABLE(non-bundled-htp,
+           AS_HELP_STRING([--enable-non-bundled-htp], [Enable the use of an already installed version of htp]),,[enable_non_bundled_htp=no])
+    AS_IF([test "x$enable_non_bundled_htp" = "xyes"], [
+        AC_ARG_WITH(libhtp_includes,
+                [  --with-libhtp-includes=DIR  libhtp include directory],
+                [with_libhtp_includes="$withval"],[with_libhtp_includes=no])
+        AC_ARG_WITH(libhtp_libraries,
+                [  --with-libhtp-libraries=DIR    libhtp library directory],
+                [with_libhtp_libraries="$withval"],[with_libhtp_libraries="no"])
 
-    if test "$with_libhtp_includes" != "no"; then
-    CPPFLAGS="${CPPFLAGS} -I${with_libhtp_includes}"
-    fi
+        if test "$with_libhtp_includes" != "no"; then
+        CPPFLAGS="${CPPFLAGS} -I${with_libhtp_includes}"
+        fi
 
-    if test "$with_libhtp_libraries" != "no"; then
-    LDFLAGS="${LDFLAGS} -L${with_libhtp_libraries}"
-    fi
+        if test "$with_libhtp_libraries" != "no"; then
+        LDFLAGS="${LDFLAGS} -L${with_libhtp_libraries}"
+        fi
 
-    AC_CHECK_HEADER(htp/htp.h,,[AC_ERROR(htp/htp.h not found ...)])
+        AC_CHECK_HEADER(htp/htp.h,,[AC_ERROR(htp/htp.h not found ...)])
 
-    LIBHTP=""
-    AC_CHECK_LIB(htp, htp_conn_create,, LIBHTP="no")
-    if test "$LIBHTP" = "no"; then
-    echo
-    echo "   ERROR! libhtp library not found"
-    echo
-    exit 1
-    fi
-    PKG_CHECK_MODULES(LIBHTPMINVERSION, htp >= 0.2.3,[libhtp_minver_found="yes"],[libhtp_minver_found="no"])
-    if test "$libhtp_minver_found" = "no"; then
-    echo
-    echo "   ERROR! libhtp was found but is not the minimum version required >=0.2.3"
-    echo
-    exit 1
-    fi
-    fi
+        LIBHTP=""
+        AC_CHECK_LIB(htp, htp_conn_create,, LIBHTP="no")
+        if test "$LIBHTP" = "no"; then
+        echo
+        echo "   ERROR! libhtp library not found"
+        echo
+        exit 1
+        fi
+        PKG_CHECK_MODULES(LIBHTPMINVERSION, htp >= 0.2.3,[libhtp_minver_found="yes"],[libhtp_minver_found="no"])
+        if test "$libhtp_minver_found" = "no"; then
+        echo
+        echo "   ERROR! libhtp was found but is not the minimum version required >=0.2.3"
+        echo
+        exit 1
+        fi
+    ])
 
    #even if we are using an installed htp lib we still need to gen Makefiles inside of htp
    AC_CONFIG_SUBDIRS([libhtp])
-   AM_CONDITIONAL([BUILD_LIBHTP], [test "$enable_non_bundled_htp" = "no"])
+   AM_CONDITIONAL([BUILD_LIBHTP], [test "x$enable_non_bundled_htp" = "xno"])
 
 # enable CUDA output
     AC_ARG_ENABLE(cuda,
-            [  --enable-cuda  Enable CUDA pattern matching],
-            [ enable_cuda=yes
-            ])
-    AC_ARG_WITH(cuda_includes,
-            [  --with-cuda-includes=DIR  cuda include directory],
-            [with_cuda_includes="$withval"],[with_cuda_includes=no])
-    AC_ARG_WITH(cuda_libraries,
-            [  --with-cuda-libraries=DIR    cuda library directory],
-            [with_cuda_libraries="$withval"],[with_cuda_libraries="no"])
+           AS_HELP_STRING([--enable-cuda], [Enable CUDA pattern matching]),,[enable_cuda=no])
+    AS_IF([test "x$enable_cuda" = "xyes"], [
+        AC_ARG_WITH(cuda_includes,
+                [  --with-cuda-includes=DIR  cuda include directory],
+                [with_cuda_includes="$withval"],[with_cuda_includes=no])
+        AC_ARG_WITH(cuda_libraries,
+                [  --with-cuda-libraries=DIR    cuda library directory],
+                [with_cuda_libraries="$withval"],[with_cuda_libraries="no"])
 
-    if test "$enable_cuda" = "yes"; then
         CFLAGS="${CFLAGS} -D__SC_CUDA_SUPPORT__"
 
         if test "$with_cuda_includes" != "no"; then
@@ -718,7 +695,8 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
             echo
             exit 1
         fi
-    fi
+    ])
+
 
 # Check for libcap-ng
 
@@ -758,11 +736,50 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
     fi
 
     AC_ARG_ENABLE(profiling,
-            [  --enable-profiling  Enable performance profiling],
-            [ enable_profiling=yes
-            ])
-    if test "$enable_profiling" = "yes"; then
-    CFLAGS="${CFLAGS} -DPROFILING"
+           AS_HELP_STRING([--enable-profiling], [Enable performance profiling]),,[enable_profiling=no])
+    AS_IF([test "x$enable_profiling" = "xyes"], [
+        CFLAGS="${CFLAGS} -DPROFILING"
+    ])
+
+# Check for DAG support.
+
+    AC_ARG_ENABLE(dag,
+	        [  --enable-dag  Enable DAG capture],
+	        [ enable_dag=yes ],
+	        [ enable_dag=no])
+    AC_ARG_WITH(dag_includes,
+            [  --with-dag-includes=DIR  dagapi include directory],
+            [with_dag_includes="$withval"],[with_dag_includes="no"])
+    AC_ARG_WITH(dag_libraries,
+            [  --with-dag-libraries=DIR  dagapi library directory],
+            [with_dag_libraries="$withval"],[with_dag_libraries="no"])
+
+    if test "$enable_dag" = "yes"; then
+
+	    if test "$with_dag_includes" != "no"; then
+            CPPFLAGS="${CPPFLAGS} -I${with_dag_includes}"
+        fi
+
+        if test "$with_dag_libraries" != "no"; then
+            LDFLAGS="${LDFLAGS} -I${with_dag_libraries}"
+        fi
+
+        AC_CHECK_HEADER(dagapi.h,DAG="yes",DAG="no")
+        if test "$DAG" != "no"; then
+            DAG=""
+	        AC_CHECK_LIB(dag,dag_open,DAG="yes",DAG="no")
+        fi
+
+        if test "$DAG" != "no"; then
+            CFLAGS="${CFLAGS} -DHAVE_DAG"
+        fi
+
+        if test "$DAG" = "no"; then
+            echo
+            echo "  ERROR! libdag library not found"
+            echo
+            exit 1
+        fi
     fi
 
 AC_SUBST(CFLAGS)
@@ -770,3 +787,21 @@ AC_SUBST(LDFLAGS)
 AC_SUBST(CPPFLAGS)
 
 AC_OUTPUT(Makefile src/Makefile)
+
+echo "
+Suricata Configuration:
+  NFQueue support:          ${enable_nfqueue}
+  IPFW support:             ${enable_ipfw}
+  PF_RING support:          ${enable_pfring}
+  Prelude support:          ${enable_prelude}
+  Unit tests enabled:       ${enable_unittests}
+  Debug output enabled:     ${enable_debug}
+  CUDA enabled:             ${enable_cuda}
+  DAG enabled:              ${enable_dag}
+  Profiling enabled:        ${enable_profiling}
+  GCC Protect enabled:      ${enable_gccprotect}
+  GCC march native enabled: ${enable_gccmarch_native}
+  GCC Profile enabled:      ${enable_gccprofile}
+  Unified native time:      ${enable_unified_native_timeval}
+  Non-bundled htp:          ${enable_non_bundled_htp}
+"
