Imported Upstream version 0.8.2

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@
 AC_INIT(configure.in)
 
     AM_CONFIG_HEADER(config.h)
-    AM_INIT_AUTOMAKE(suricata, 0.1)
+    AM_INIT_AUTOMAKE(suricata, 0.8.2)
 
     AC_LANG_C
     AC_PROG_CC_C99
@@ -23,7 +23,35 @@ AC_INIT(configure.in)
             exit 1
             ])
 
+    AC_DEFUN([LIBNET_FAIL_WARN],[
+            echo
+            echo "*************************************************************************"
+            echo "   Warning! libnet version 1.1.x could not be found in " $1
+            echo "   Reject keywords will not be supported."
+            echo "   If you require reject support plese install libnet 1.1.x. "
+            echo "   If libnet is not installed in a non-standard location please use the"
+            echo "   --with-libnet-includes and --with-libnet-libraries configure options"
+            echo "*************************************************************************"
+            echo
+            ])
+
+    dnl get gcc version
+    AC_MSG_CHECKING([gcc version])
+            gccver=$($CC -dumpversion)
+            gccvermajor=$(echo $gccver | cut -d . -f1)
+            gccverminor=$(echo $gccver | cut -d . -f2)
+            gccvernum=$(expr $gccvermajor "*" 100 + $gccverminor)
+    AC_MSG_RESULT($gccver)
+
+    if test "$gccvernum" -ge "400"; then
+            dnl gcc 4.0 or later
+            CFLAGS="$CFLAGS -Wextra"
+    else
+            CFLAGS="$CFLAGS -W"
+    fi
+
     CFLAGS="$CFLAGS -Wall -fno-strict-aliasing"
+    CFLAGS="$CFLAGS -Wno-unused-parameter"
 
 # Checks for programs.
     AC_PROG_AWK
@@ -32,12 +60,11 @@ AC_INIT(configure.in)
     AC_PROG_INSTALL
     AC_PROG_LN_S
     AC_PROG_MAKE_SET
-    AC_PROG_RANLIB
 
 # Checks for libraries.
 
 # Checks for header files.
-    AC_CHECK_HEADERS([arpa/inet.h inttypes.h limits.h netinet/in.h stdint.h stdlib.h string.h sys/socket.h sys/time.h unistd.h])
+    AC_CHECK_HEADERS([arpa/inet.h inttypes.h limits.h netdb.h netinet/in.h poll.h signal.h stdint.h stdlib.h string.h syslog.h sys/prctl.h sys/socket.h sys/syscall.h sys/time.h unistd.h windows.h winsock2.h ws2tcpip.h])
 
 # Checks for typedefs, structures, and compiler characteristics.
     AC_C_INLINE
@@ -77,6 +104,10 @@ AC_INIT(configure.in)
 		    ;;
            *-*-linux*)
                     #for now do nothing
+                    ;;
+           *-*-mingw32*)
+                    CFLAGS="${CFLAGS} -DOS_WIN32"
+                    LDFLAGS="${LDFLAGS} -lws2_32"
                     ;;
 	   *)
 		AC_MSG_WARN([unsupported OS this may or may not work])
@@ -142,6 +173,36 @@ AC_INIT(configure.in)
         CFLAGS="${CFLAGS} ${SECCFLAGS}"
         LDFLAGS="${LDFLAGS} ${SECLDFLAGS}"
     fi
+
+#enable profile generation
+    AC_ARG_ENABLE(gccprofile,
+            [  --enable-gccprofile Enable gcc profile info i.e -pg flag is set],
+            [ enable_gccprofile=yes
+            ])
+
+    if test "$enable_gccprofile" = "yes"; then
+    CFLAGS="${CFLAGS} -pg"
+    fi
+
+#enable gcc march=native gcc 4.2 or later
+    AC_ARG_ENABLE(gccmarch_native,
+            [  --enable-gccmarch-native Enable gcc march=native gcc 4.2 and later only],
+            [ enable_gccmarch_native=yes
+            ])
+
+    if test "$enable_gccmarch_native" = "yes"; then
+        if test "$gccvernum" -ge "402"; then
+                dnl gcc 4.2 or later
+                CFLAGS="$CFLAGS -march=native"
+        else
+                echo
+                echo "   You specified --enable-gccmarch-native but looks like you are running gcc < 4.2"
+                echo "   Please update your version of gcc or remove this option from configure."
+                echo
+                exit 1
+        fi
+    fi
+
 #libpcre
     AC_ARG_WITH(libpcre_includes,
             [  --with-libpcre-includes=DIR  libpcre include directory],
@@ -170,6 +231,20 @@ AC_INIT(configure.in)
     echo
     exit 1
     fi
+
+   AC_TRY_COMPILE([ #include <pcre.h> ],
+   [ int eo = 0; eo |= PCRE_EXTRA_MATCH_LIMIT_RECURSION; ],
+   [ pcre_match_limit_recursion_available=yes ], [:]
+   )
+   if test "$pcre_match_limit_recursion_available" != "yes"; then
+    CFLAGS="${CFLAGS} -DNO_PCRE_MATCH_RLIMIT"
+    echo
+    echo "   Warning! pcre extra opt PCRE_EXTRA_MATCH_LIMIT_RECURSION not found"
+    echo "   This could lead to potential DoS please upgrade to pcre >= 6.5"
+    echo "   Continuing for now...."
+    echo "   from www.pcre.org."
+    echo
+   fi
 
 #libyaml
     AC_ARG_WITH(libyaml_includes,
@@ -304,6 +379,39 @@ AC_INIT(configure.in)
     fi
     fi
 
+#enable support for IPFW
+    AC_ARG_ENABLE(ipfw,
+            [  --enable-ipfw  Enable FreeBSD IPFW support for inline IDP],
+            [ enable_ipfw=yes
+            ])
+    if test "$enable_ipfw" = "yes"; then
+        CFLAGS="$CFLAGS -DIPFW"
+    fi
+
+#prelude
+
+    AC_ARG_ENABLE(prelude,
+            [  --enable-prelude  Enable Prelude support for alerts],
+            [ enable_prelude=yes
+            ])
+    if test "$enable_prelude" = "yes"; then
+        CFLAGS="$CFLAGS -DPRELUDE"
+        AM_PATH_LIBPRELUDE(0.9.9, , AC_MSG_ERROR(Cannot find libprelude: Is libprelude-config in the path?), no)
+        if test "x${LIBPRELUDE_CFLAGS}" != "x"; then
+            CPPFLAGS="${CPPFLAGS} ${LIBPRELUDE_CFLAGS}"
+        fi
+
+        if test "x${LIBPRELUDE_LDFLAGS}" != "x"; then
+            LDFLAGS="${LDFLAGS} ${LIBPRELUDE_LDFLAGS}"
+        fi
+
+        if test "x${LIBPRELUDE_LIBS}" != "x"; then
+            LDFLAGS="${LDFLAGS} ${LIBPRELUDE_LIBS}"
+        fi
+
+    fi
+
+
 #libnet
     AC_ARG_WITH(libnet_includes,
             [  --with-libnet-includes=DIR     libnet include directory],
@@ -314,53 +422,69 @@ AC_INIT(configure.in)
             [with_libnet_libraries="$withval"],[with_libnet_libraries="no"])
 
     if test "x$with_libnet_includes" != "xno"; then
-    CPPFLAGS="${CPPFLAGS} -I${with_libnet_includes}"
+        CPPFLAGS="${CPPFLAGS} -I${with_libnet_includes}"
+        libnet_dir="${with_libnet_includes}"
+    else
+        libnet_dir="/usr/include /usr/local/include /usr/local/include/libnet11 /opt/local/include"
     fi
 
     if test "x$with_libnet_libraries" != "xno"; then
-    LDFLAGS="${LDFLAGS} -L${with_libnet_libraries}"
+        LDFLAGS="${LDFLAGS} -L${with_libnet_libraries}"
     fi
 
+    LIBNET_DETECT_FAIL="no"
     LIBNET_INC_DIR=""
-    AC_MSG_CHECKING("for libnet.h version 1.1.x")
-    libnet_dir="/usr/include /usr/local/include /usr/local/include/libnet11 /opt/local/include"
+
     for i in $libnet_dir; do
     if test -r "$i/libnet.h"; then
-    LIBNET_INC_DIR="$i"
+        LIBNET_INC_DIR="$i"
     fi
     done
 
+    AC_MSG_CHECKING(for libnet.h version 1.1.x)
     if test "$LIBNET_INC_DIR" != ""; then
-    if eval "grep LIBNET_VERSION $LIBNET_INC_DIR/libnet.h | grep -v 1.1 >/dev/null"; then
-    FAIL_MESSAGE("libnet 1.1.x (libnet.h)", $tmp)
-    fi
+        if eval "grep LIBNET_VERSION $LIBNET_INC_DIR/libnet.h | grep -v 1.1 >/dev/null"; then
+            AC_MSG_RESULT(no)
+            LIBNET_DETECT_FAIL="yes"
+            LIBNET_FAIL_WARN($libnet_dir)
+        else
+            AC_MSG_RESULT(yes)
+        fi
 
-    #CentOS, Fedora, Ubuntu-LTS, Ubuntu all set defines to the same values. libnet-config seems
-    #to have been depreciated but all distro's seem to include it as part of the package.
-    LLIBNET=""
-    AC_CHECK_LIB(net, libnet_write,, LLIBNET="no")
-    if test "$LLIBNET" != "no"; then
-    CFLAGS="${CFLAGS} -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H"
-    fi
-    AC_MSG_RESULT($i)
+        #CentOS, Fedora, Ubuntu-LTS, Ubuntu all set defines to the same values. libnet-config seems
+        #to have been depreciated but all distro's seem to include it as part of the package.
+        if test "$LIBNET_DETECT_FAIL" = "no"; then
+            LLIBNET=""
+            AC_CHECK_LIB(net, libnet_write,, LLIBNET="no")
+            if test "$LLIBNET" != "no"; then
+                CFLAGS="${CFLAGS} -DHAVE_LIBNET11 -D_BSD_SOURCE -D__BSD_SOURCE -D__FAVOR_BSD -DHAVE_NET_ETHERNET_H"
+            else
+            #if we displayed a warning already no reason to do it again.
+                if test "$LIBNET_DETECT_FAIL" = "no"; then
+                    LIBNET_DETECT_FAIL="yes"
+                    LIBNET_FAIL_WARN($libnet_dir)
+                fi
+            fi
+
+            # see if we have the patched libnet 1.1
+            # http://www.inliniac.net/blog/2007/10/16/libnet-11-ipv6-fixes-and-additions.html
+            #
+            # To prevent duping the lib link we reset LIBS after this check. Setting action-if-found to NULL doesn't seem to work
+            # see: http://blog.flameeyes.eu/2008/04/29/i-consider-ac_check_lib-harmful
+            if test "$LIBNET_DETECT_FAIL" = "no"; then
+                LLIBNET=""
+                TMPLIBS="${LIBS}"
+                AC_CHECK_LIB(net, libnet_build_icmpv6_unreach,, LLIBNET="no")
+                if test "$LLIBNET" != "no"; then
+                    CFLAGS="$CFLAGS -DHAVE_LIBNET_ICMPV6_UNREACH"
+                fi
+                LIBS="${TMPLIBS}"
+            fi
+        fi
     else
-    AC_MSG_RESULT(no)
-    AC_MSG_ERROR("libnet 1.1.x could not be found.  please download and install the library from http://sourceforge.net/projects/libnet-dev/")
+        LIBNET_DETECT_FAIL="yes"
+        LIBNET_FAIL_WARN($libnet_dir)
     fi
-
-# see if we have the patched libnet 1.1
-# http://www.inliniac.net/blog/2007/10/16/libnet-11-ipv6-fixes-and-additions.html
-    LLIBNET=""
-
-#To prevent duping the lib link we reset LIBS after this check. Setting action-if-found to NULL doesn't seem to work
-#see: http://blog.flameeyes.eu/2008/04/29/i-consider-ac_check_lib-harmful
-    TMPLIBS="${LIBS}"
-    AC_CHECK_LIB(net, libnet_build_icmpv6_unreach,, LLIBNET="no")
-    if test "$LLIBNET" != "no"; then
-    CFLAGS="$CFLAGS -DHAVE_LIBNET_ICMPV6_UNREACH"
-    fi
-    LIBS="${TMPLIBS}"
-
 # libpfring (currently only supported for libpcap enabled pfring)
 # Error on the side of caution. If libpfring enabled pcap is being used and we don't link against -lpfring compilation will fail.
     AC_ARG_ENABLE(pfring,
@@ -370,6 +494,8 @@ AC_INIT(configure.in)
     if test "$enable_pfring" = "yes"; then
     CFLAGS="$CFLAGS -DHAVE_PFRING"
     fi
+
+#We have to set CFLAGS for AC_TRY_COMPILE as it doesn't pay attention to CPPFLAGS
     AC_ARG_WITH(libpfring_includes,
             [  --with-libpfring-includes=DIR  libpfring include directory],
             [with_libpfring_includes="$withval"],[with_libpfring_includes=no])
@@ -386,16 +512,25 @@ AC_INIT(configure.in)
     fi
 
     LIBPFRING=""
-    AC_CHECK_LIB(pfring, pfring_open,, LIBPFRING="no")
+    AC_CHECK_LIB(pfring, pfring_set_cluster,, LIBPFRING="no")
     if test "$LIBPFRING" = "no"; then
         if test "enable_pfring" = "yes"; then
         echo
-        echo "   ERROR! --enable-pfring was passed but the library was not found, go get it"
+        echo "   ERROR! --enable-pfring was passed but the library was not found or version is >4, go get it"
         echo "   from http://www.ntop.org/PF_RING.html"
         echo
         exit 1
         fi
     fi
+
+    AC_TRY_COMPILE([ #include <pfring.h> ],
+    [ pfring *pd; pd = pfring_open("eth1", 1,  1515, 1); pfring_set_cluster(pd, 99, cluster_round_robin); ],
+    [ pfring_cluster_type_available=yes ], [:]
+    )
+    if test "$pfring_cluster_type_available" = "yes"; then
+     CFLAGS="${CFLAGS} -DHAVE_PFRING_CLUSTER_TYPE"
+    fi
+
 
 # libpcap
     AC_ARG_WITH(libpcap_includes,
@@ -447,6 +582,15 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
     CFLAGS="${CFLAGS} -DUNITTESTS"
     fi
 
+# enable native timeval for unified alert output
+    AC_ARG_ENABLE(unified-native-timeval,
+            [  --enable-unified-native-timeval  Use native timeval for unified outputs],
+            [ enable_unified_native_timeval=yes
+            ])
+    if test "$enable_unified_native_timeval" = "yes"; then
+    CFLAGS="${CFLAGS} -DUNIFIED_NATIVE_TIMEVAL"
+    fi
+
 # enable debug output
     AC_ARG_ENABLE(debug,
             [  --enable-debug  Enable debug output],
@@ -457,6 +601,11 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
     fi
 
 #libhtp
+    AC_ARG_ENABLE(nonbundled-htp,
+            [  --enable-nonbundled-htp Enable the use of an already installed version of htp],
+            [enable_non_bundled_htp=yes],[enable_non_bundled_htp=no]
+            )
+    if test "$enable_non_bundled_htp" = "yes"; then
     AC_ARG_WITH(libhtp_includes,
             [  --with-libhtp-includes=DIR  libhtp include directory],
             [with_libhtp_includes="$withval"],[with_libhtp_includes=no])
@@ -482,8 +631,48 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
     echo
     exit 1
     fi
+    fi
 
-    #LDFLAGS="${LDFLAGS}  -lhtp"
+   #even if we are using an installed htp lib we still need to gen Makefiles inside of htp
+   AC_CONFIG_SUBDIRS([libhtp])
+   AM_CONDITIONAL([BUILD_LIBHTP], [test "$enable_non_bundled_htp" = "no"])
+
+# enable CUDA output
+    AC_ARG_ENABLE(cuda,
+            [  --enable-cuda  Enable CUDA pattern matching],
+            [ enable_cuda=yes
+            ])
+    AC_ARG_WITH(cuda_includes,
+            [  --with-cuda-includes=DIR  cuda include directory],
+            [with_cuda_includes="$withval"],[with_cuda_includes=no])
+    AC_ARG_WITH(cuda_libraries,
+            [  --with-cuda-libraries=DIR    cuda library directory],
+            [with_cuda_libraries="$withval"],[with_cuda_libraries="no"])
+
+    if test "$enable_cuda" = "yes"; then
+        CFLAGS="${CFLAGS} -D__SC_CUDA_SUPPORT__"
+
+        if test "$with_cuda_includes" != "no"; then
+            CPPFLAGS="${CPPFLAGS} -I${with_cuda_includes}"
+        else
+            CPPFLAGS="${CPPFLAGS} -I/usr/include/cuda"
+        fi
+
+        if test "$with_cuda_libraries" != "no"; then
+            LDFLAGS="${LDFLAGS} -L${with_cuda_libraries}"
+        fi
+
+        AC_CHECK_HEADER(cuda.h,,[AC_ERROR(cuda.h not found ...)])
+
+        LIBCUDA=""
+        AC_CHECK_LIB(cuda, cuArray3DCreate,, LIBCUDA="no")
+        if test "$LIBCUDA" = "no"; then
+            echo
+            echo "   ERROR! libcuda library not found"
+            echo
+            exit 1
+        fi
+    fi
 
 
 AC_SUBST(CFLAGS)
@@ -491,4 +680,3 @@ AC_SUBST(LDFLAGS)
 AC_SUBST(CPPFLAGS)
 
 AC_OUTPUT(Makefile src/Makefile)
-
