Imported Upstream version 1.0.0

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@
 AC_INIT(configure.in)
 
     AM_CONFIG_HEADER(config.h)
-    AM_INIT_AUTOMAKE(suricata, 0.9.2)
+    AM_INIT_AUTOMAKE(suricata, 1.0.0)
 
     AC_LANG_C
     AC_PROG_CC_C99
@@ -50,7 +50,9 @@ AC_INIT(configure.in)
             CFLAGS="$CFLAGS -W"
     fi
 
-    CFLAGS="$CFLAGS -Wall -fno-strict-aliasing"
+    # remove optimization options that break our code
+    # VJ 2010/06/27: no-tree-pre added. It breaks ringbuffers code.
+    CFLAGS="$CFLAGS -Wall -fno-strict-aliasing -fno-tree-pre"
     CFLAGS="$CFLAGS -Wno-unused-parameter"
     CFLAGS="$CFLAGS -std=gnu99"
 
@@ -61,6 +63,16 @@ AC_INIT(configure.in)
     AC_PROG_INSTALL
     AC_PROG_LN_S
     AC_PROG_MAKE_SET
+
+    AC_PATH_PROG(HAVE_PKG_CONFIG, pkg-config, "no")
+    if test "$HAVE_PKG_CONFIG" = "no"; then
+    echo
+    echo "   ERROR! pkg-config not found, go get it  "
+    echo "   http://pkg-config.freedesktop.org/wiki/ "
+    echo "   or install from your distribution       "
+    echo
+    exit 1
+    fi
 
 # Checks for libraries.
 
@@ -184,10 +196,22 @@ AC_INIT(configure.in)
     AC_ARG_ENABLE(gccmarch_native,
            AS_HELP_STRING([--enable-gccmarch-native], [Enable gcc march=native gcc 4.2 and later only]),,[enable_gccmarch_native=yes])
     AS_IF([test "x$enable_gccmarch_native" = "xyes"], [
-        if test "$gccvernum" -ge "402"; then
-                dnl gcc 4.2 or later
-                CFLAGS="$CFLAGS -march=native"
-        fi
+        case $host in
+	    *darwin*|*Darwin*)
+		if test "$gccvernum" -ge "403"; then
+                    dnl gcc 4.3 or later
+                    CFLAGS="$CFLAGS -march=native"
+		else
+		    enable_gccmarch_native=no
+		fi
+		;;
+	    *)
+		if test "$gccvernum" -ge "402"; then
+                    dnl gcc 4.2 or later
+                    CFLAGS="$CFLAGS -march=native"
+		fi
+		;;
+	esac
     ])
 
 #libpcre
@@ -620,6 +644,13 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
         CFLAGS="${CFLAGS} -DDEBUG"
     ])
 
+# enable debug validation functions & macro's output
+    AC_ARG_ENABLE(debug-validation,
+           AS_HELP_STRING([--enable-debug-validation], [Enable (debug) validation code output]),,[enable_debug_validation=no])
+    AS_IF([test "x$enable_debug_validation" = "xyes"], [
+        CFLAGS="${CFLAGS} -DDEBUG_VALIDATION"
+    ])
+
 #libhtp
     AC_ARG_ENABLE(non-bundled-htp,
            AS_HELP_STRING([--enable-non-bundled-htp], [Enable the use of an already installed version of htp]),,[enable_non_bundled_htp=no])
@@ -664,7 +695,7 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
 
 # enable CUDA output
     AC_ARG_ENABLE(cuda,
-           AS_HELP_STRING([--enable-cuda], [Enable CUDA pattern matching]),,[enable_cuda=no])
+           AS_HELP_STRING([--enable-cuda], [Enable experimental CUDA pattern matching]),,[enable_cuda=no])
     AS_IF([test "x$enable_cuda" = "xyes"], [
         AC_ARG_WITH(cuda_includes,
                 [  --with-cuda-includes=DIR  cuda include directory],
@@ -796,6 +827,7 @@ Suricata Configuration:
   Prelude support:          ${enable_prelude}
   Unit tests enabled:       ${enable_unittests}
   Debug output enabled:     ${enable_debug}
+  Debug validation enabled: ${enable_debug_validation}
   CUDA enabled:             ${enable_cuda}
   DAG enabled:              ${enable_dag}
   Profiling enabled:        ${enable_profiling}
