d/suricata.init: actually bail out if missing /etc/default/suricata file
Previously, the message appeared but no action (exit) was being taken.

This was reported in debian bug #850889

Reported-by: Christoph Biedl <debian.axhn@manchmal.in-ulm.de>
Signed-off-by: Arturo Borrero Gonzalez <arturo@debian.org>

diff --git a/debian/suricata.init b/debian/suricata.init
--- a/debian/suricata.init
+++ b/debian/suricata.init
@@ -12,13 +12,14 @@
 #                    match against a set of known attacks.
 ### END INIT INFO
 
+# Source function library.
 . /lib/lsb/init-functions
 
-# Source function library.
 if test -f /etc/default/suricata; then
 	. /etc/default/suricata
 else
-	echo "/etc/default/suricata is missing... bailing out!"
+	echo "/etc/default/suricata is missing... bailing out!" >&2
+	exit 1
 fi
 
 # We'll add up all the options above and use them
